version: '3.8'

services:
  gitfailguard:
    image: gitfailguard
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    container_name: gitfailguard
